apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: urbanobservatory-event-source
spec:
  image: github.com/markusthoemmes/knative-websocket-eventsource/cmd
  args: 
    - '--source=wss://api.usb.urbanobservatory.ac.uk/stream'
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: testchannel